<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_6.0_component-title-icon component-title-_997e9a</name>
   <tag></tag>
   <elementGuidId>45870370-8fed-42d9-92a1-647e5c9f4a56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapse-goblue']/div/table/tbody/tr[5]/td/table/tbody/tr[2]/td[3]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>component-title-icon component-title-check fa fa-check-circle</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse-goblue&quot;)/div[@class=&quot;card-body&quot;]/table[@class=&quot;table margin-top-10&quot;]/tbody[1]/tr[5]/td[1]/table[@class=&quot;table&quot;]/tbody[1]/tr[2]/td[3]/i[@class=&quot;component-title-icon component-title-check fa fa-check-circle&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse-goblue']/div/table/tbody/tr[5]/td/table/tbody/tr[2]/td[3]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/i</value>
   </webElementXpaths>
</WebElementEntity>
