<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log out</name>
   <tag></tag>
   <elementGuidId>fdf05014-2b02-42b7-a6fc-fcb00be55b3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Log out')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item.menu-topbar-dropdown-logout</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item menu-topbar-dropdown-logout</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost/action/user/logout?ossn_ts=1655443552&amp;ossn_token=5fa59b773807e06b1b3038b5e21f87a83f8ac67faa97fc89dfb6f346dd4de40d</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log out</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;opensource-socalnetwork&quot;]/div[@class=&quot;ossn-page-container&quot;]/div[@class=&quot;topbar&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-9 col-md-3 text-right right-side&quot;]/div[@class=&quot;topbar-menu-right&quot;]/ul[1]/li[@class=&quot;ossn-topbar-dropdown-menu&quot;]/div[@class=&quot;dropdown&quot;]/ul[@class=&quot;dropdown-menu multi-level show&quot;]/li[3]/a[@class=&quot;dropdown-item menu-topbar-dropdown-logout&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log out')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Settings'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrator'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='---'])[1]/preceding::a[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Cover'])[1]/preceding::a[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log out']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/action/user/logout?ossn_ts=1655443552&amp;ossn_token=5fa59b773807e06b1b3038b5e21f87a83f8ac67faa97fc89dfb6f346dd4de40d']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/ul/li[3]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/action/user/logout?ossn_ts=1655443552&amp;ossn_token=5fa59b773807e06b1b3038b5e21f87a83f8ac67faa97fc89dfb6f346dd4de40d' and (text() = 'Log out' or . = 'Log out')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OSSN'])[1]/following::a[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have poked admin 1!'])[1]/preceding::a[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/action/user/logout?ossn_ts=1655308371&amp;ossn_token=25aa9d37cd1f0d988f546721a527940b6b591e6c82cc60d7285ffe549d106919']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/ul/li[2]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/action/user/logout?ossn_ts=1655308371&amp;ossn_token=25aa9d37cd1f0d988f546721a527940b6b591e6c82cc60d7285ffe549d106919' and (text() = 'Log out' or . = 'Log out')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/action/user/logout?ossn_ts=1655302414&amp;ossn_token=67c4aadc31f6134832aa82cabd5e31f7004c0d41e03218ba641d290f00ccc104']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/action/user/logout?ossn_ts=1655302414&amp;ossn_token=67c4aadc31f6134832aa82cabd5e31f7004c0d41e03218ba641d290f00ccc104' and (text() = 'Log out' or . = 'Log out')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/action/user/logout?ossn_ts=1655302297&amp;ossn_token=e1d65a31baee568cd999d22dc9046b72ed88be63a48f1d0faba84a00a3984b09']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/action/user/logout?ossn_ts=1655302297&amp;ossn_token=e1d65a31baee568cd999d22dc9046b72ed88be63a48f1d0faba84a00a3984b09' and (text() = 'Log out' or . = 'Log out')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/action/user/logout?ossn_ts=1655300781&amp;ossn_token=33bcb171bdab6278a5c8ce1149b9413e5eb5c1b4f699d5f44229544706e60b6d']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/action/user/logout?ossn_ts=1655300781&amp;ossn_token=33bcb171bdab6278a5c8ce1149b9413e5eb5c1b4f699d5f44229544706e60b6d' and (text() = 'Log out' or . = 'Log out')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/action/user/logout?ossn_ts=1655282124&amp;ossn_token=24321a7c9c9069276505fc2679769b9ef34f5ea8e99ac3eb068474d2e066e6d2']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/action/user/logout?ossn_ts=1655282124&amp;ossn_token=24321a7c9c9069276505fc2679769b9ef34f5ea8e99ac3eb068474d2e066e6d2' and (text() = 'Log out' or . = 'Log out')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Die Änderung wurde gespeichert'])[1]/preceding::a[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/action/user/logout?ossn_ts=1655281918&amp;ossn_token=034fd93a6b1877250b95e7d308d7c695385d9782dfb2f8cabb956c8142cc4f8c']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/action/user/logout?ossn_ts=1655281918&amp;ossn_token=034fd93a6b1877250b95e7d308d7c695385d9782dfb2f8cabb956c8142cc4f8c' and (text() = 'Log out' or . = 'Log out')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User updated!'])[1]/preceding::a[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/action/user/logout?ossn_ts=1655281740&amp;ossn_token=0ae40c46c0f36115eedd1d0b33fc5a1762c015790d7d177edbc41ce6b8496c59']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/action/user/logout?ossn_ts=1655281740&amp;ossn_token=0ae40c46c0f36115eedd1d0b33fc5a1762c015790d7d177edbc41ce6b8496c59' and (text() = 'Log out' or . = 'Log out')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/action/user/logout?ossn_ts=1655281409&amp;ossn_token=8a0b22fd247121278c22043d8b6035740df4cafcd5dd3a665d85f590e726fade']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/action/user/logout?ossn_ts=1655281409&amp;ossn_token=8a0b22fd247121278c22043d8b6035740df4cafcd5dd3a665d85f590e726fade' and (text() = 'Log out' or . = 'Log out')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/action/user/logout?ossn_ts=1655281302&amp;ossn_token=1f24f3adb5338c734f6755daed959db6b69d89d83ca0539b598f115c61510584']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/action/user/logout?ossn_ts=1655281302&amp;ossn_token=1f24f3adb5338c734f6755daed959db6b69d89d83ca0539b598f115c61510584' and (text() = 'Log out' or . = 'Log out')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/action/user/logout?ossn_ts=1655267831&amp;ossn_token=5a0bd4649d60fd218e6c6f811ba9f9c7a52ef01cca4d8905ac243997721d8ed0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/action/user/logout?ossn_ts=1655267831&amp;ossn_token=5a0bd4649d60fd218e6c6f811ba9f9c7a52ef01cca4d8905ac243997721d8ed0' and (text() = 'Log out' or . = 'Log out')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/action/user/logout?ossn_ts=1655267375&amp;ossn_token=c4805d9e86befb9896c4b8ed00687b322f40bd563ee24ec1d219ce7737c6b0fe']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/action/user/logout?ossn_ts=1655267375&amp;ossn_token=c4805d9e86befb9896c4b8ed00687b322f40bd563ee24ec1d219ce7737c6b0fe' and (text() = 'Log out' or . = 'Log out')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/action/user/logout?ossn_ts=1655267247&amp;ossn_token=67224922192e8a0015c69ecdcbe3ec3dc55da7c65a5a863ef56f281cbea9f2c0']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/action/user/logout?ossn_ts=1655267247&amp;ossn_token=67224922192e8a0015c69ecdcbe3ec3dc55da7c65a5a863ef56f281cbea9f2c0' and (text() = 'Log out' or . = 'Log out')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost/action/user/logout?ossn_ts=1655261189&amp;ossn_token=39438163c4e73c48aeb186336d5cb94099248769141fb8aab8a7af3b16ea5aec']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost/action/user/logout?ossn_ts=1655261189&amp;ossn_token=39438163c4e73c48aeb186336d5cb94099248769141fb8aab8a7af3b16ea5aec' and (text() = 'Log out' or . = 'Log out')]</value>
   </webElementXpaths>
</WebElementEntity>
